title: Seethalakshmi
logo: /assets/img/img_8998.jpg
description: I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
