title: Seethalakshmi
logo: /assets/img/IMG_8998.JPG
description: I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
Linkedin: (https://linkedin.com/in/seethalakshmi-v-1689a228)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
